stages:
  data_ingestion:
    cmd: py src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    # params:
    # - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: py src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: py src/feature_engineering.py
    deps:
    - data/interim
    - src/feature_engineering.py
    # params:
    # - feature_engineering.max_features
    outs:
    - data/processed
  model_building:
    cmd: py src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    # params:
    # - model_building.n_estimators
    # - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: py src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json
# params:
# - dvclive/params.yaml
# metrics:
# - dvclive/metrics.json
# plots:
# - dvclive/plots/metrics:
#     x: step
